name: Sync to Repo B

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Push to Repo B
        env:
          REPO_B_TOKEN: ${{ secrets.REPO_B_TOKEN }}
        run: |
          git remote add repo-b https://${REPO_B_TOKEN}@github.com/shariqhasan29/repo-b.git
          git push repo-b main:sync --force