name: Sync to Repo B

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "$REPO_B_SSH_KEY" > ~/.ssh/repo_b_key
          chmod 600 ~/.ssh/repo_b_key
          ssh-keyscan github.com >> ~/.ssh/known_hosts 2>/dev/null

      - name: Set Git Identity
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Push to Repo B via SSH
        env:
          REPO_B_SSH_KEY: ${{ secrets.REPO_B_SSH_KEY }}
        run: |
          export GIT_SSH_COMMAND="ssh -i ~/.ssh/repo_b_key -o StrictHostKeyChecking=no"
          git remote add repo-b git@github.com:shariqhasan29/repo-b.git
          git push repo-b main:sync --force

      - name: Success
        run: echo "Successfully synced Repo A (main) → Repo B (sync) via SSH!"