name: Sync to Repo B

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      # DEBUG 1: Show if secret is loaded
      - name: Debug - Print Token Info
        env:
          REPO_B_TOKEN: ${{ secrets.REPO_B_TOKEN }}
        run: |
          if [ -z "$REPO_B_TOKEN" ]; then
            echo "ERROR: REPO_B_TOKEN is EMPTY or NOT SET!"
            exit 1
          else
            echo "Token length: ${#REPO_B_TOKEN}"
            echo "Token preview: ${REPO_B_TOKEN:0:8}..."
          fi

      # DEBUG 2: Add remote with full URL echo
      - name: Add Repo B Remote (with debug)
        env:
          REPO_B_TOKEN: ${{ secrets.REPO_B_TOKEN }}
        run: |
          echo "Adding remote with URL:"
          echo "https://x-access-token:***@github.com/shariqhasan29/repo-b.git"
          
          git remote add repo-b "https://x-access-token:${REPO_B_TOKEN}@github.com/shariqhasan29/repo-b.git" || \
          git remote set-url repo-b "https://x-access-token:${REPO_B_TOKEN}@github.com/shariqhasan29/repo-b.git"

          echo "Remote added. Verifying..."
          git remote -v

      # DEBUG 3: Test remote URL explicitly
      - name: Test Remote URL
        run: |
          echo "Final remote URL:"
          git remote get-url repo-b

      # DEBUG 4: Try a dry-run push to see auth
      - name: Dry-run push (test auth)
        env:
          REPO_B_TOKEN: ${{ secrets.REPO_B_TOKEN }}
        run: |
          echo "Testing authentication with dry-run..."
          git push repo-b main:sync --dry-run

      # FINAL: Real push
      - name: Push to Repo B (main → sync)
        env:
          REPO_B_TOKEN: ${{ secrets.REPO_B_TOKEN }}
        run: |
          git push repo-b main:sync --force

      - name: Success
        run: echo "Sync completed successfully!"