name: Sync to Repo B

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo A
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add Repo B as remote
        run: |
          git remote add repo-b https://x-access-token:${{ secrets.REPO_B_TOKEN }}@github.com/shariqhasan29/repo-b.git
          git fetch repo-b sync

      - name: Push changes to Repo B (sync branch)
        run: |
          git push repo-b main:sync --force
